### ISSUE TITLE
v3.0.0 not able to post

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#130]
Was not able to post after fresh installation. After turning on "Security Maths Question" it worked fine

**Comment by C-Lodder** [comment]
@betteryouthanme - I've fixed this:

https://github.com/JoomJunk/shoutbox/commit/87918e7ec7e5d84ac8f6d94cb512846baaf7dbab

On line 807 of helper.php, change 0 to 1
