### ISSUE TITLE
v3.0.0 Hide smileys option

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#131]
As discussed in the forum, it would be nice to hide the smileys when site loads and then use the toggle to let them show up. So just the other way round as it presently is. Maybe optional in backend?

**Comment by C-Lodder** [comment]
I've added in this option: https://github.com/JoomJunk/shoutbox/commit/df6a4ac78d57c55de3058769bcac2cf87ca843f6
