### ISSUE TITLE
v3.0.0 Security methods

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#132]
1)  Nice idea to deactivate the post button if reCaptcha is not entered but even if i enter the right code it is not getting active again -> can't post (only if both security methods are enabled)

2) Deactivate buttons for both methods if (math) questions are not filled in?

3) Still showing both, math and ReCaptcha, if logged in. It's confusing and should be not shown for registered users at all (maybe optional in backend?)

4)Just realized that the math question is not working at all? Even as guest you don't have to enter the right result.

5) Error if not filling in the ReCaptcha:
Fatal error: Call to undefined method JFactory::enqueueMessage() in C:\xampp\htdocs\joomla\modules\mod_shoutbox\helper.php on line 751

**Comment by C-Lodder** [comment]
@betteryouthanme, thank you for the effort you're making to help test this. Can I just confirm that you're using Joomla 3.3.x?

**Comment by betteryouthanme** [comment]
Joomla 3.3.3 yes

**Comment by C-Lodder** [comment]
https://github.com/JoomJunk/shoutbox/commit/e00840d4638e32f79fe18124e1c3c12cb7219b5f
