### ISSUE TITLE
Frame marked text with bb code tags

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#134]
So if "Lorem ipsum" is marked it becomes
"&lt;b>Lorem ipsum&lt;/b>"

**Comment by wilsonge** [comment]
What do you mean by this?

**Comment by betteryouthanme** [comment]
You mark a word or phrase in the text you entered. If you now click on the bold button the word/phrase gets surrounded by the bold bbcode tags.

**Comment by C-Lodder** [comment]
@betteryouthanme - Just on a side note, I've added you to our Special Thanks page:

http://joomjunk.co.uk/extras-page/special-thanks.html

Do you have a website I can add for you?

**Comment by betteryouthanme** [comment]
Now that's not necessary but if you want add rprclan.com, where your shoutbox is in use.

**Comment by C-Lodder** [comment]
@betteryouthanme - ok will add your website. By the way, we've released v3.0.0 of the shoutbox if you didn't already know ;)

**Comment by C-Lodder** [comment]
I've improved the BBCode which now fixes this issue

https://github.com/JoomJunk/shoutbox/commit/af1c780656817364c9df7ace3388468a549b1571
