### ISSUE TITLE
Show images as thumbnail

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#135]
When image link, show a thumbnail and on click open full image as Lightbox

**Comment by C-Lodder** [comment]
@betteryouthanme - I'm not too sure about this one. Problem being is if a post contains text AND and an image, how is it possible to display the thumbnail? As for the lightbox, this is a big task to develop one from scratch. As an alternative relying on a 3rd party lightbox is something I prefer not doing. Maybe @wilsonge has some different views

**Comment by wilsonge** [comment]
you just have the lightbox trigger on the hyperlink rather than going to the page. That part isn't too hard I don't think. You don't have to have a button to open the lightbox. This would also be 3rd party images only. Having people submit images in shouts is way too complex for a 'simple' module like the shoutbox. I'd consider it for version 3.1 I think.

**Comment by betteryouthanme** [comment]
Yes thought that it might be causing more problems then it'd be acutally useful. Just throwing in what comes to mind ;)

**Comment by C-Lodder** [comment]
Cause I'm that nice :)

https://github.com/JoomJunk/shoutbox/commit/99c9fdd633d02ab70ea280cd22d8bdcac92a9e84

**Comment by betteryouthanme** [comment]
Thanks :)
To make it work for Bootstrap3 i had to adjust the codestyle in default.php:
Added a  few more div classes (modal-dialog, modal-content, ..)
and removed "hide" in jj-image-modal div

http://getbootstrap.com/javascript/#static-example

**Comment by C-Lodder** [comment]
@betteryouthanme - ah ok. I might add a Bootstrap 3 option in the styling parameters. Currently there's "Bootstrap" and "UIKit"

**Comment by wilsonge** [comment]
But that modal isn't going to open in UIKit as is atm right?
