### ISSUE TITLE
User ability to delete own posts

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#136]

**Comment by C-Lodder** [comment]
+1

**Comment by wilsonge** [comment]
I'm open to this. But I think I'd add a timelimit (say 2-3 minutes in which a user can delete a post) so they can delete places where they make huge typos but they can't go back and wipe out a full half of a conversation.

**Comment by C-Lodder** [comment]
done: https://github.com/JoomJunk/shoutbox/commit/f2cb2bcbf589fef56c4558fc0db782e013ad5b0e
