### ISSUE TITLE
Adding a shoutbox archive

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#137]
so you can reread older posts. Maybe as component and additonally a search plugin.

**Comment by C-Lodder** [comment]
A component would be the best solution, but would then mean a massive overhaul of the shoutbox as we would most likely utilize it as much as possible. So a temporary solution could be to have a parameter in the backend that brings up a modal box and loads all shouts with some sort of ajax load on scroll perhaps.

**Comment by wilsonge** [comment]
We've considered a component several times. But based on the feedback I've seen on other extensions people are more reluctant to use a component for this kind of thing than a module. It's a tough one. It may end up with us supporting two extensions "Shoutbox Basic" and "Shoutbox Advanced"

**Comment by betteryouthanme** [comment]
Hm i see.. What about this:
Let's say your shoutbox displays 10 shouts. If you scroll down now to the first post, a link or button appears to show +10 posts. This can be done until the total amount of posts stored is reached.

**Comment by C-Lodder** [comment]
I like this idea a lot actually. What I suggested as a parameter in the backend but much prefer the idea of having it in the frontend.

**Comment by C-Lodder** [comment]
https://github.com/JoomJunk/shoutbox/commit/15139403530e9f1a0136487fbd2ab7e96926f5c6
