### ISSUE TITLE
Jomsocial avatar integration

### ISSUE THREAD

**Issue by PLFoxNET** [JoomJunk/shoutbox#140]

**Comment by wilsonge** [comment]
Use JomSocial Avatars
To acquire a path to a JomSocial Avatar, you can simply request a cUser object and call a simple getThumbAvatar function to retrieve the avatar url.

include_once JPATH_ROOT.'/components/com_community/libraries/core.php';
// Get CUser object
$user = CFactory::getUser($userid);
$avatarUrl = $user->getThumbAvatar();
echo '<img src="'.$avatarUrl.'">';

**Comment by wilsonge** [comment]
Will get on this tonight with the given docs

**Comment by C-Lodder** [comment]
Please try with the following code:

```
$core = JPATH_ROOT.'/components/com_community/libraries/core.php';

if (file_exists($core))
{
	include_once JPATH_ROOT.'/components/com_community/libraries/core.php';
}

$cuser 		= CFactory::getUser($user->id);
$avatarUrl 	= $cuser->getThumbAvatar();

$url = '<img src="'.$avatarUrl.'" height="30" width="30">';
```

**Comment by C-Lodder** [comment]
https://github.com/JoomJunk/shoutbox/commit/ae0a277b837f32544c89a64a0089b86469d8b184
