### ISSUE TITLE
Error when math question left empty (v3.0.0 beta3)

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#141]
Getting following error when Math question enabled and not filled in or incorrect:

Fatal error: Call to undefined method JFactory::enqueueMessage() in C:\xampp\htdocs\joomla\modules\mod_shoutbox\helper.php on line 744

**Comment by wilsonge** [comment]
Fixed with https://github.com/JoomJunk/shoutbox/commit/a8dae07e14b1eb5b30e60bbf3fec254d3ae3ca8d
