### ISSUE TITLE
Add proper error reporting below shoutbox

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/shoutbox#143]
- [x] Error shown when name field is empty
- [x] Error shown when message field is empty
- [x] Error shown for Ajax submit post failure
- [x] Error shown for Ajax get post failure
- [x] Error shown for incorrect security answer

**Comment by C-Lodder** [comment]
- [x] Error shown when name field is empty
- [x] Error shown when message field is empty
- [ ] Error shown for Ajax submit post failure
- [ ] Error shown for Ajax get post failure

**Comment by wilsonge** [comment]
Started cleanup #167

**Comment by wilsonge** [comment]
Did some more work in https://github.com/JoomJunk/shoutbox/commit/56e8195ef98ffb3a0dfdeeeff23fa4a3f54bcb1d
