### ISSUE TITLE
Make name input mandatory for guests

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#145]
or use a default term if left empty

**Comment by C-Lodder** [comment]
Ahh, I believe this is a small bug. I have added in a HTML5 `required` attribute to the name field which worked for the previous version of the shoutbox: https://github.com/JoomJunk/shoutbox/blob/master/mod_shoutbox/tmpl/default.php#L97

I'll fix this in the next minor update

**Comment by C-Lodder** [comment]
I've nearly fixed this but just revamping the error reporting when the name or message fields are blank. Will get this committed tonight :)

**Comment by C-Lodder** [comment]
I've added an option for the admin to select whether the name is required or not. If it's not required, the "generic name" option fades in allowing the admin to choose a name that will be used if one isn't entered when submitting a shout.

https://github.com/JoomJunk/shoutbox/commit/82b4280088b8981940186aee1a084aacf711a845
