### ISSUE TITLE
Make bbcode for links more intuitive

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#146]
So shoutbox detects link if they entered in the following way:
<code>[url]https://www.bing.com[/url]</code>
becomes
<code>https://www.bing.com</code>
or
<code>«link»</code>

Of course the manuall text option should be obtained..
Maybe you have some ideas for it.

**Comment by C-Lodder** [comment]
The way I wrote this is you are able to insert a link **and** custom text. For example, rather than just having a long URL, you can use:

[url=http://google.co.uk] Google [/url]

Which would become 

[Google](http://google.co.uk)

**Comment by betteryouthanme** [comment]
Yes a popup would be great.
It's just that i've seen a lots of "[url=]https://whatever.qw[/url]"
messages lately on our site

**Comment by C-Lodder** [comment]
For the time being as we want to get this release out fairly soon with the fixes, I might just have an alert box showing the user how to do this. And then in v3.1.0, I will sort it all out properly

**Comment by C-Lodder** [comment]
Used a popover for this to keep things simplified: https://github.com/JoomJunk/shoutbox/commit/e0473e5f25c74c84373a1c85e06fa06f6b7d6fda

**Comment by betteryouthanme** [comment]
as you brought up modal for images, maybe you guys can do the same now for entering links?
Somethinh like this i've in mind:
![screenshot_1](https://cloud.githubusercontent.com/assets/8537297/10012057/a9c05e5a-6103-11e5-8df4-974752d16e65.png)

**Comment by C-Lodder** [comment]
@betteryouthanme - I've now added this: https://github.com/JoomJunk/shoutbox/commit/d72fe9e800c6912925df379df549797f4dc08e98

It's not a modal, but instead a small dropdown with the input fields

**Comment by C-Lodder** [comment]
@betteryouthanme I've just pushed a big commit with BBCode/smiley changes and Bootstrap 3 integration. If you could try it, that would be highly appreciated

**Comment by betteryouthanme** [comment]
works fine. Great job!
Sometimes the images overlaps the modal if its too wide. Right now i added to the css file:
#jj-image-modal .modal-body > img { width: 100%; }
But maybe there's a better solution?

**Comment by C-Lodder** [comment]
@betteryouthanme - I'll give this a quick try and a 4k image and then add a fix. Thanks for reporting

**Comment by C-Lodder** [comment]
I've just tested a large image in Firefox and Chrome, but I don't have overlapping issues with the width, only the height overlaps

**Comment by betteryouthanme** [comment]
Yes for b2 height is overlapping and for b3 only width.. Good luck ;)

**Comment by C-Lodder** [comment]
@betteryouthanme - Does this fix the issue for you? https://github.com/JoomJunk/shoutbox/commit/25b135e119372412e5b59cb5a54c4ac89e899830
