### ISSUE TITLE
JJ Shoutbox and Advanced Module Manager homepage assignment

### ISSUE THREAD

**Issue by wojsmol** [JoomJunk/shoutbox#150]
Welcome
If I use the assignment module to homepage using the Advanced Module Manager from @nonumber when I try to send a message I get the following error:
Mod_shoutbox module is not published, you do not have access to it, or it's not Assigned to the current menu item.
If the module is assigned simply to specific menu item sending a message  is working properly.

Specifications
Joomla 3.4.1
JJ Shoutbox version 3.1.2
Advanced Module Manager 4.22.4 FREE

**Comment by C-Lodder** [comment]
@wojsmol - thank you for reporting this issue. We will look into this tomorrow during the day.

**Comment by wojsmol** [comment]
Hello
@C-Lodder Were you able to determine something, I ask because the problem still occurs.

Current specifications:
Joomla 3.4.3
JJ Shoutbox version 5.0.1
Advanced Module Manager 5.1.1 FREE

**Comment by C-Lodder** [comment]
@wojsmol - Sorry for the long wait on this. I'll look into this now and try to replicate the issue.

**Comment by C-Lodder** [comment]
@wojsmol - Ok I've digged into the code for this and it does appear to be an issue with Advanced Module Manager. In the Joomla core, there's an Ajax component and within this, it checks if the module is enabled by checking if the *ID* is **not 0** as show here:

https://github.com/joomla/joomla-cms/blob/staging/components/com_ajax/ajax.php#L56

I'm not sure exactly how Advanced Module Manager manipulates modules but it appears to be setting the *ID* to **0**, therefore throwing the error you saw.

If could could contact @nonumber, and let me know the response, that would be appreciated. i can try and provide some form of work around if a patch to his extension cannot be made

**Comment by wilsonge** [comment]
For reference the nonumber issue created is at https://www.nonumber.nl/forum/advancedmodulemanager/39970-jj-shoutbox-and-advanced-module-manager-homepage-assignment and I've added some more information there that hopefully Peter can work with.

Basically however we call com_ajax (a core Joomla component) on submission of data. As this isn't the component that is assigned to your homepage the request fails because the module isn't published on that page.

**Comment by wojsmol** [comment]
@wilsonge Additional information - due to strange glitches on nonumber.nl issue has been assigned to the wrong account - already reported it to Peter.

**Comment by wojsmol** [comment]
Welcome
@C-Lodder @wilsonge Thank you for your help.
Regards

**Comment by nonumber** [comment]
Just some in-depth info on the fix:
I added an extra check in the Advanced Module Manager plugin so it only gets triggered and does its thing when the page type is 'html'. So it falls back completely on core behavior on json and other non-html formats.

**Comment by C-Lodder** [comment]
@nonumber - Thanks Peter. Have these changes been applied to the dev site I sent you or do we need to test with the AWW-dev version?

**Comment by nonumber** [comment]
Have been applied on the test site. But you can also install the latest dev to make sure the changes have made it to the zip correctly :)
https://www.nonumber.nl/development-releases

**Comment by C-Lodder** [comment]
@nonumber - Shoutbox is now working as expected. Thank you for doing this Peter, much appreciated.

**Comment by wilsonge** [comment]
Awesome - that makes a lot of sense actually :) Thanks @nonumber
