### ISSUE TITLE
Add ability for user to edit own post

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/shoutbox#173]
- [x] - Add edit button next to delete button
- [x] - Initialize Ajax request on click
- [x] - Check timestamp in database and compare with current one
- [x] - Get shout data from the database and append to the form fields
- [x] - Change submit button text to "Update"
- [x] - Update the shout 
- [x] - Add button to cancel the edit
- [x] - Make a parameter
- [x] - Use Language strings
- [x] - Revert back to "submit" button after update
- [x] - Add support for "enter to submit"
- [x] - Styling

### Bugs:

- The data attribute `shout-id` is updating in the HTML but it's not retrieving the new value when editing a different post after the first was edit. It's as if the events are not delegated when they actually are

**Comment by wilsonge** [comment]
You really do need a time limit on this. People shouldn't be able to edit their mosts more than 5-10 seconds after making them in a shoutbox

**Comment by C-Lodder** [comment]
That's the plan

**Comment by C-Lodder** [comment]
all complete
