### ISSUE TITLE
Upgrade to recaptcha 2

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/shoutbox#175]

**Comment by wilsonge** [comment]
Repo for the new php library https://github.com/google/recaptcha

**Comment by wilsonge** [comment]
Btw technically this is a b/c break because global keys won't work (we actually hit that problem when I moved JJ to recaptcha v2). How do we want to deal with that?

**Comment by C-Lodder** [comment]
We can add a message in the script.php I suppose

**Comment by wilsonge** [comment]
Could work. As long as we do something - otherwise some people's recaptcha systems may well break

**Comment by C-Lodder** [comment]
See: https://github.com/JoomJunk/shoutbox/commit/1ce536272fb7b9a0964eb909e31e8e7f7f16e369

Send it to you on FB earlier on
