### ISSUE TITLE
Issues from betteryouthanme

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/shoutbox#183]
- [x] - Avatars in the history are not getting resized, they appear in original size, too large
- [x] - After opening the link/image entering form, there's no closing option
- [x] - link/image form: The forms do not differ from each other, so you don't know which one is actually opened.

**Comment by betteryouthanme** [comment]
"Delete all existing posts as admin" was not meant asan issue, just a step to reproduce the issue with the refreshing problem.

**Comment by C-Lodder** [comment]
ahh ok. will remove that then

**Comment by C-Lodder** [comment]
All fixed.
