### ISSUE TITLE
Kunena avatar integration

### ISSUE THREAD

**Issue by wilsonge** [JoomJunk/shoutbox#19]
Look into integrating with Kunena avatars

**Comment by betteryouthanme** [comment]
Will it be available already in version 3.0.0?

**Comment by C-Lodder** [comment]
Probably not 3.0.0 as this version is supposed to be for the Ajax integration along with improvements of what is currently available. This version will be released very soon so the Kunena avatar integration will most likely be in the next update ;)

**Comment by C-Lodder** [comment]
@betteryouthanme - all done :)

https://github.com/JoomJunk/shoutbox/commit/e292abd39e2b9debe150a5c28525d2f309f132c1

**Comment by betteryouthanme** [comment]
looks beautiful (rprclan.com) Thanks a lot ;)
I know it's not stable but could not wait..
