### ISSUE TITLE
Remove use of $_SESSION

### ISSUE THREAD

**Issue by wilsonge** [JoomJunk/shoutbox#213]
This token is used when PHP submission is done - however we need to ensure that we use the Joomla API through `JSession`

**Comment by C-Lodder** [comment]
No need for this anymore

**Comment by wilsonge** [comment]
I'd still like us to move to `JSession` if we can one day. It just not a priority anymore. Just leave it open as an issue for all eternity until we have some time to try and debug the stupid thing
