### ISSUE TITLE
Undefined variable in helper.php

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#220]
PHP error log gives following error:
PHP Notice:  : href in C:\inetpub\wwwroot\www\modules\mod_shoutbox\helper.php on line 608

**Comment by C-Lodder** [comment]
Hmm odd. I'll look into this later on today. I thought I'd fixed this issue after removing `extract()` :/

**Comment by C-Lodder** [comment]
@betteryouthanme - I have turned my error reporting to the maximum and still cannot replicate this error. I'm aware that you add cutting edge code to the Shoutbox when we push updates to Github, so please ensure you have added ALL code and not jus some of it.

I'd suggest:

- [Downloading the ZIP file for the development branch](https://github.com/JoomJunk/shoutbox/archive/development.zip)
- Extracting `mod_shoutbox` from the ZIP
- Zip up the `mod_shoutbox` folder
- Install

**Comment by betteryouthanme** [comment]
hey, just tried again with the new version and if i activate  Error Reporting Development in Joomla i get this message above each post.
Also each time the shoutbox refresh i get a message like on the screenshot:
![26-01-2016 12-23-25](https://cloud.githubusercontent.com/assets/8537297/12579367/bef4b2bc-c427-11e5-8710-f51218477223.png)

As soon as i change to none error reporting all is find. Guess it's not really important just tripped over it and thought to report here

**Comment by C-Lodder** [comment]
On line 616 to 619, you will see the following:
```
foreach ($dom->getElementsByTagName('a') as $node) 
{
	$href = $node->getAttribute('href');
}
```

Could you replace this with:

```
$href = array();
foreach ($dom->getElementsByTagName('a') as $node) 
{
	$href = $node->getAttribute('href');
}
var_dump($href);
```

and let me know what it dumps out

**Comment by betteryouthanme** [comment]
for me the mentioned code is between lines 602-605.
However if i change the code i get:
array(0) { }
Notice: Array to string conversion in C:\inetpub\wwwroot\www\modules\mod_shoutbox\helper.php on line 618

**Comment by betteryouthanme** [comment]
if i change Link profile to none in the back-end i don't get a error message. So must have something to do with Kunena profile link.

**Comment by C-Lodder** [comment]
Hmmm, odd. Would I have able to get FTP access or a backup of your site to test and fix? If so, please send details via email (admin@joomjunk.co.uk)

**Comment by C-Lodder** [comment]
Ahh crap. The error occurs when you're logged out. Looking into this now

**Comment by C-Lodder** [comment]
Fixed. Releasing an update now

**Comment by betteryouthanme** [comment]
thanks works like a charm!
