### ISSUE TITLE
Display date/time relative to time of shout

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/shoutbox#226]
E.g .... 1 day and 14 hours ago

**Comment by wilsonge** [comment]
How are we planning to display this. It isn't going to fit in the space next to the title I don't think

**Comment by C-Lodder** [comment]
Yee of little faith

**Comment by wilsonge** [comment]
I will write the code. No problem. Just need you to tell me how you want it rendered

**Comment by C-Lodder** [comment]
It will appear where the current date/time appears. 

Bare in mind this will be an additional `option` in the "Date" settings, not a new parameter

**Comment by C-Lodder** [comment]
done
