### ISSUE TITLE
Convert line 996 and 1053 of helper to language strings

### ISSUE THREAD

**Issue by C-Lodder** [JoomJunk/shoutbox#248]

**Comment by wilsonge** [comment]
Fixed these two + several more with https://github.com/JoomJunk/shoutbox/commit/b652140ad4ca525cf11a7839bfa08614b25ede5b

**Comment by wilsonge** [comment]
Ughh i missed 1053

**Comment by C-Lodder** [comment]
done: https://github.com/JoomJunk/shoutbox/commit/32c4408d60e5f3a1d4e03b4cb048c89b80d73dd2
